//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersImport
    {
        public int ID { get; set; }
        public int TypePartnerID { get; set; }
        public int PartnerID { get; set; }
        public string Director { get; set; }
        public string Email { get; set; }
        public string NumPhone { get; set; }
        public int AdresID { get; set; }
        public double INN { get; set; }
        public int Reiting { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual TypePartner TypePartner { get; set; }
    }
}
