//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductImport
    {
        public int ID { get; set; }
        public int NameProductID { get; set; }
        public int PartnerID { get; set; }
        public double Quantity { get; set; }
        public System.DateTime DateSale { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual ProductName ProductName { get; set; }
    }
}
